require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'booking' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'


  target 'bookingTests' do
    # Stripe
  pod 'Stripe', '~> 14.0.0'

  # Install additional dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'booking-tvOS' do
  # Pods for booking-tvOS

  target 'booking-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
